# Generated by Django 5.0.2 on 2025-06-15 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='artwork/')),
                ('status', models.CharField(choices=[('FOR_SALE', 'For Sale'), ('SOLD', 'Sold'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('medium', models.CharField(choices=[('GRAPHITE', 'Graphite'), ('OIL', 'Oil')], max_length=20)),
                ('category', models.CharField(choices=[('PORTRAIT', 'Portrait'), ('FIGURE', 'Figure')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('reference_images', models.ImageField(blank=True, null=True, upload_to='commissions/references/')),
                ('size', models.CharField(max_length=100)),
                ('medium', models.CharField(choices=[('GRAPHITE', 'Graphite'), ('OIL', 'Oil')], max_length=20)),
                ('category', models.CharField(choices=[('PORTRAIT', 'Portrait'), ('FIGURE', 'Figure')], max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
