# Generated by Django 5.0.2 on 2025-06-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='backing',
            field=models.CharField(choices=[('PAPER', 'Paper'), ('STRETCH_CANVAS', 'Stretch Canvas'), ('CANVAS_BOARD', 'Canvas Board')], default='PAPER', max_length=20),
        ),
        migrations.AddField(
            model_name='artwork',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
