# Generated by Django 5.0.2 on 2025-06-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_paypalaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paypalaccount',
            options={'ordering': ['title', 'email'], 'verbose_name': 'PayPal Account', 'verbose_name_plural': 'PayPal Accounts'},
        ),
        migrations.AddField(
            model_name='paypalaccount',
            name='title',
            field=models.CharField(blank=True, help_text="A title to identify this PayPal account (e.g., 'Production', 'Sandbox')", max_length=100, null=True),
        ),
    ]
