# Generated by Django 5.0.2 on 2025-06-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='artwork/thumbnails/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='tile_image',
            field=models.ImageField(blank=True, null=True, upload_to='artwork/tiles/'),
        ),
    ]
