# Generated by Django 5.0.2 on 2025-06-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0007_artwork_thumbnail_image_artwork_tile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
